# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mikael Engström, Friluftslivare 
email: mikael@engstrom.live
description: >- # this means to ignore newlines until "baseurl:"
  My first tests with jekyll just to try it out, will probably delete later.

# Build settings
remote_theme: coogie/oscailte
plugins:
  - jekyll-feed

# 
domain: 3nm1.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://3nm1.github.io  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder

# Theme specific settings
oscailte:
  posts_url:
  google_analytics:
  show_excerpts: true
  social:
    #twitter: username
    github: 3nm1
    #dribbble: username
    #facebook: username
    #flickr: username
    #instagram: username
    linkedin: mikael-engström
    #mastodon: https://instance.url/@username
    #pinterest: username
    telegram: mikael_3nm1
    #keybase: username
    rss: rss
  strings:
    skip_to_main_content: "Gå till huvudinnehåll"
    x_minute_read: "$x$ minut läst"
    hero_title: "Välkommen!"
    recent_posts: "Nya inlägg"
    view_all: "Visa alla"
    read_full: "Läs hela"
    disqus_enable_javascript: 'Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus</a>.'

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
